-- 用途：
-- 1. 为全新数据库快速初始化当前版本的完整表结构
-- 2. 初始化后会把 alembic_version 标记到当前 head：20260723_100000
--
-- 约定：
-- - Alembic 仍然是 schema 变更的唯一事实来源
-- - 本脚本是当前结构的快照，适合新环境快速建库
-- - 后续新增/修改表结构时，需要同步新增 Alembic migration，并刷新本脚本

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    nickname VARCHAR(32) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    wechat_openid VARCHAR(128),
    wechat_unionid VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_wechat_openid ON users (wechat_openid);
CREATE INDEX IF NOT EXISTS ix_users_wechat_unionid ON users (wechat_unionid);

CREATE TABLE IF NOT EXISTS families (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    cover_url VARCHAR(500),
    invite_code VARCHAR(20) NOT NULL UNIQUE,
    owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    max_members INTEGER NOT NULL DEFAULT 2,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_families_invite_code ON families (invite_code);

CREATE TABLE IF NOT EXISTS family_members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id INTEGER NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(16) NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_family_members_family_user UNIQUE (family_id, user_id),
    CONSTRAINT uq_family_members_user UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS dishes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id INTEGER NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    image_url VARCHAR(500),
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS meal_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id INTEGER NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    requester_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    cook_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL,
    planned_date DATE NOT NULL,
    planned_time TIME,
    note VARCHAR(500),
    accepted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS meal_order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_order_id INTEGER NOT NULL REFERENCES meal_orders(id) ON DELETE CASCADE,
    dish_id INTEGER NOT NULL REFERENCES dishes(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL DEFAULT 1,
    note VARCHAR(255),
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS order_status_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_order_id INTEGER NOT NULL REFERENCES meal_orders(id) ON DELETE CASCADE,
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    operator_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    note VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS meal_reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_order_id INTEGER NOT NULL REFERENCES meal_orders(id) ON DELETE CASCADE,
    reviewer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    rating INTEGER NOT NULL,
    content VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_meal_reviews_order UNIQUE (meal_order_id)
);

CREATE TABLE IF NOT EXISTS wechat_subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_type VARCHAR(40) NOT NULL,
    available_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_wechat_subscriptions_user_event UNIQUE (user_id, event_type)
);

CREATE INDEX IF NOT EXISTS ix_wechat_subscriptions_user_id
ON wechat_subscriptions (user_id);

CREATE TABLE IF NOT EXISTS wechat_notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    meal_order_id INTEGER REFERENCES meal_orders(id) ON DELETE SET NULL,
    event_type VARCHAR(40) NOT NULL,
    template_id VARCHAR(128) NOT NULL,
    page VARCHAR(255) NOT NULL,
    payload JSON NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    error_message VARCHAR(500),
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_wechat_notifications_meal_order_id
ON wechat_notifications (meal_order_id);
CREATE INDEX IF NOT EXISTS ix_wechat_notifications_recipient_id
ON wechat_notifications (recipient_id);
CREATE INDEX IF NOT EXISTS ix_wechat_notifications_status
ON wechat_notifications (status);

CREATE TABLE IF NOT EXISTS chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id INTEGER NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_chat_messages_family_id_id
ON chat_messages (family_id, id);

CREATE TABLE IF NOT EXISTS chat_read_states (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id INTEGER NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    last_read_message_id INTEGER REFERENCES chat_messages(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_chat_read_states_family_user UNIQUE (family_id, user_id)
);

CREATE TABLE IF NOT EXISTS alembic_version (
    version_num VARCHAR(32) NOT NULL PRIMARY KEY
);

INSERT INTO alembic_version (version_num)
VALUES ('20260723_100000')
ON CONFLICT (version_num) DO NOTHING;

DELETE FROM alembic_version
WHERE version_num <> '20260723_100000';

COMMIT;
