"""init

Revision ID: 5488d1b3e9c6
Revises: d9ab13427836
Create Date: 2026-07-21 17:06:49.848844
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5488d1b3e9c6'
down_revision = 'd9ab13427836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
