"""init

Revision ID: d9ab13427836
Revises: 50655bce3ae5
Create Date: 2026-07-21 17:06:33.194758
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd9ab13427836'
down_revision = '50655bce3ae5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
